### ISSUE TITLE
Redesign rule filtering language

### ISSUE THREAD

**Issue by soutaro** [soutaro/querly#26]
```yml
config:
  - rule: sample.test
    on: /test
  - rule: rails.app.controller
    on: /app/controllers
  - rule: capybara
    on: /features
  - rule: minitest
    on:
      - /test
      - /features
```
