### ISSUE TITLE
[Feature Request] Add schema check for config file

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/querly#56]
To save Querly users from typos on `querly.yml`, I strongly suggest checking the schema of `querly.yml`.

For example, because I couldn't notice a typo like `except` and `expect`, my configuration (`rule2`) didn't work well. 😓 

```yaml
check:
  - path: /
    rules:
      - except: rule1
      - expect: rule2
```

When there are mistakes in the configuration like above, I hope `querly check` or `querly test` command fails immediately and outputs an easy message to understand.

For example:

```
$ querly test
Error: Querly configuration in /path/to/my/project/querly.yml is invalid:
       - Unexpected property "expect".
```

What do you think about this suggestion?
