### ISSUE TITLE
Not defined rules on `check` section

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/querly#69]
Even if the following incorrect `querly.yml` is given, Querly succeeds.
I think good that the `querly test` command could tell such incorrectness.

```yaml
# querly.yml
rules:
  - id: sample.foo
    pattern:
      - self.p
      - self.pp
    message: Delete debug print

check:
  - path: /
    rules:
      - except: sample.test #<= Not defined!
  - path: /test
    rules:
      - append: sample.test #<= Not defined!
```

```shell-session
$ querly test
Checking rule id uniqueness...
Checking rule patterns...
Tested 1 rules with 0 tests.
  All tests green!
```
